/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fairTA.main

import fairTA.main.Controller

fun main(args: Array<String>) {
//    generateInstances(numSources = 15, numTargets = 500)
    val controller = Controller()
    controller.parseArgs(args)
    controller.populateInstance()
    controller.run()
}
